app/main/forms.py
from flask_wtf import Form, widgets
from wtforms import StringField, BooleanField, SelectField, SelectMultipleField, IntegerField, SubmitField, TextField
from wtforms.widgets import TextArea
from wtforms.validators import Required, Length, Email, Regexp, EqualTo


GRADE_CHOICES = [
		('JK', 'JK'),
		('K', 'K'),
		('1st', '1st'),
		('2nd', '2nd'),
		('3rd', '3rd'),
		('4th', '4th'),
		('5th', '5th'),
		('6th', '6th'),
		('7th', '7th'),
		('8th', '8th'),
		('9th', '9th'),
		('10th', '10th'),
		('11th', '11th'),
		('12th', '12th')
	]

SPORT_LEVELS = [
		('Varsity', 'Varsity'),
		('Junior Varisty', 'Junior Varisty'),
		('Sophomore', 'Sophomore'),
		('Freshman', 'Freshman'),
		('Other', 'Other')
	]

CARD_TYPES = [
		('Visa', 'Visa'),
		('Master Card', 'Master Card'),
		('American Express', 'American Express'),
		('Discover Card', 'Discover Card')
	]

GRAD_CARD_LAYOUTS = [
		('Layout A', 'A'),
		('Layout B', 'B'),
		('Layout C', 'C'),
		('Layout D', 'D'),
		('Layout E', 'E'),
		('Layout F', 'F'),
		('Layout G', 'G'),
		('Layout H', 'H'),
		('Layout I', 'I'),
		('Layout J', 'J'),
		('Layout K', 'K'),
		('Layout L', 'L')
	]

GRAD_CARD_COLORS = [
		('Black', 'Black'),
		('Blue', 'Blue'),
		('Brown', 'Brown'),
		('Coral', 'Coral'),
		('Dark Blue', 'Dark Blue'),
		('Dark Green', 'Dark Green'),
		('Gold', 'Gold'),
		('Grey', 'Grey'),
		('Light Blue', 'Light Blue'),
		('Light Green', 'Light Green'),
		('Maroon', 'Maroon'),
		('Orange', 'Orange'),
		('Purple', 'Purple'),
		('Red', 'Red'),
		('Royal Blue', 'Royal Blue'),
		('Tan Texture', 'Tan Texture'),
		('White', 'White'),
		('Yellow', 'Yellow')
	]

GRAD_CARD_QUANTITIES = [
		('25 for $95', '25 for $95'),
		('50 for $158', '50 for $158'),
		('75 for $190', '75 for $190'),
		('100 for $225', '100 for $225')
	]

GRAD_CARD_IMAGE_TYPES = [
		('Color', 'Color'),
		('Black and White', 'Black and White')
	]

GRAD_CARD_FONTS = [
		('Same as Sample', 'Same as Sample'),
	  	('Algerian', 'Algerian'),
	  	('Amazone', 'Amazone'),
	  	('Aparajita', 'Aparajita'),
	  	('Bradley Hand', 'Bradley Hand'),
	  	('Brush Script', 'Brush Script'),
	  	('Candara', 'Candara'),
	  	('Century Gothic', 'Century Gothic'),
	  	('Chaparral Pro', 'Chaparral Pro'),
	  	('Corel', 'Corel'),
	  	('Coronet', 'Coronet'),
	  	('Desdemona', 'Desdemona'),
	  	('Eccentric STD', 'Eccentric STD'),
	  	('Edwardian Script', 'Edwardian Script'),
	  	('Fifth Ave', 'Fifth Ave'),
	  	('Footlight MT Light', 'Footlight MT Light'),
	  	('Future', 'Future'),
	  	('Impact', 'Impact'),
	  	('Kinn MT', 'Kinn MT'),
	  	('Minion Pro', 'Minion Pro'),
	  	('Optima', 'Optima'),
	  	('ProvLite', 'ProvLite'),
	  	('Segoe Script', 'Segoe Script'),
	  	('Sirona', 'Sirona'),
	  	('Technical', 'Technical')
  	]

GRAD_CARD_IMAGE_BORDERS = [
		('None', 'None'),
		('Artistic Edge', 'Artistic Edge'),
		('Line', 'Line')
	]


class UnderclassPreorderForm(Form):
	school = StringField('School', validators=[Required()])
	student_name = StringField('Student Name', validators=[Required()])
	grade = SelectField('Grade', choices=GRADE_CHOICES, validators=[Required()])
	homeroom = StringField('Homeroom', validators=[Required()])
	sport_name = StringField('Sport Name')
	jersey_number = StringField('Jersey Number')
	level = SelectField('Level', choices=SPORT_LEVELS)
	parent_name = StringField('Parent Name', validators=[Required()])
	address = StringField('Address', validators=[Required()])
	city = StringField('City', validators=[Required()])
	state = StringField('State', validators=[Required()])
	zipcode = StringField('Zip Code', validators=[Required()])
	phone = StringField('Phone Number', validators=[Required()])
	email = StringField('Email', validators=[Required()])
	card_type = SelectField('Credit Card Type', choices=CARD_TYPES, validators=[Required()])
	expiration_date = StringField('Expiration Date', validators=[Required()])
	verification_code = StringField('Verification Code', validators=[Required()])
	item_1 = StringField('Item 1', validators=[Required()])
	item_1_price = StringField('Item 1 Price', validators=[Required()])
	item_2 = StringField('Item 2')
	item_2_price = StringField('Item 2 Price')
	item_3 = StringField('Item 3')
	item_3_price = StringField('Item 3 Price')
	item_4 = StringField('Item 4')
	item_4_price = StringField('Item 4 Price')
	submit = SubmitField('Submit Order')


class RequestInfoForm(Form):
	name = StringField('Name', validators=[Required()])
	organization = StringField('Organization', validators=[Required()])
	position = StringField('Position', validators=[Required()])
	address = StringField('Address', validators=[Required()])
	city = StringField('City', validators=[Required()])
	state = StringField('State', validators=[Required()])
	zipcode = StringField('Zip Code', validators=[Required()])
	phone = StringField('Phone Number', validators=[Required()])
	email = StringField('Email', validators=[Required()])
	current_photog = StringField('Current Photographer')
	comments_questions = TextField('Comments or Questions', widget=TextArea())
	submit = SubmitField('Submit')


class RenewContractForm(Form):
	as_outlined = BooleanField('I Agree to the Program as Outlined in Contract Terms')
	e_signature = StringField('Electronic Signature', validators=[Required()])
	seventeen_eighteen = BooleanField('2017-2018')
	eighteen_nineteen = BooleanField('2018-2019 $500 Signing Bonus')
	nineteen_twenty = BooleanField('2019-2020 $750 Signing Bonus')
	additional_requests = TextField('Additional Requests', widget=TextArea())
	school = StringField('School', validators=[Required()])
	address = StringField('Address', validators=[Required()])
	city = StringField('City', validators=[Required()])
	state = StringField('State', validators=[Required()])
	zipcode = StringField('Zip Code', validators=[Required()])
	phone = StringField('Phone Number', validators=[Required()])
	email = StringField('Email', validators=[Required()])
	comments_questions = TextField('Comments or Questions', widget=TextArea())
	submit = SubmitField('Submit')


class PhotoClassForm(Form):
	name = StringField('Name', validators=[Required()])
	address = StringField('Address')
	city = StringField('City')
	state = StringField('State')
	zipcode = StringField('Zip Code')
	phone = StringField('Phone Number')
	email = StringField('Email')
	submit = SubmitField('Submit')

# GET CC INFO?

class GraduateCardOrderForm(Form):
	school = StringField('School', validators=[Required()])
	student_name = StringField('Student Name', validators=[Required()])
	parent_name = StringField('Parent Name', validators=[Required()])
	address = StringField('Address', validators=[Required()])
	city = StringField('City', validators=[Required()])
	state = StringField('State', validators=[Required()])
	zipcode = StringField('Zip Code', validators=[Required()])
	phone = StringField('Phone Number', validators=[Required()])
	email = StringField('Email', validators=[Required()])
	quantity = SelectField('Quantity', choices=GRAD_CARD_QUANTITIES),
	image_type = SelectField('Image Type', choices=GRAD_CARD_IMAGE_TYPES),
	card_type = SelectField('Credit Card Type', choices=CARD_TYPES, validators=[Required()])
	card_number = StringField('Card Number', validators=[Required()])
	expiration_date = StringField('Expiration Date', validators=[Required()])
	verification_code = StringField('Verification Code', validators=[Required()])
	layout = SelectField('Layout', choices=GRAD_CARD_LAYOUTS, validators=[Required()])
	background_color = SelectField('Color', choices=GRAD_CARD_COLORS, validators=[Required()])
	font = SelectField('Font', choices=GRAD_CARD_FONTS, validators=[Required()])
	font_color = SelectField('Font Color', choices=GRAD_CARD_COLORS, validators=[Required()])
	image_border = SelectField('Image Border', choices=GRAD_CARD_IMAGE_BORDERS, validators=[Required()])
	imprinting = StringField('Card Imprinting', widget=TextArea())
	promo_code = StringField('Promo Code')
	password = StringField('Password', validators=[Required()])
	pose_number = StringField('Pose Number', validators=[Required()])
	submit = SubmitField('Submit Order')

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views

app/main/views.py
from flask import render_template, flash, session, redirect, url_for, current_app

from . import main
from ..models import UnderclassPreorder, RequestInfo, RenewedContract, PhotoClass, GraduateCardOrder
from forms import UnderclassPreorderForm, RequestInfoForm, RenewContractForm, PhotoClassForm, GraduateCardOrderForm
from helpers import flash_errors

@main.route('/')
def index():
	return render_template('main/index.html')

@main.route('/enter_password')
def enter_password():
	return render_template('main/enter_password.html')

@main.route('/underclass_preorder', methods=['GET', 'POST'])
def underclass_preorder():
	form = UnderclassPreorderForm()
	if form.validate_on_submit():
		underclass_preorder = UnderclassPreorder(
				school=form.school.data,
				student_name=form.student_name.data,
				grade=form.grade.data,
				homeroom=form.homeroom.data,
				sport_name=form.sport_name.data,
				jersey_number=form.jersey_number.data,
				level=form.level.data,
				parent_name=form.parent_name.data,
				address=form.address.data,
				city=form.city.data,
				state=form.state.data,
				zipcode=form.zipcode.data,
				phone=form.phone.data,
				email=form.email.data,
				card_type=form.card_type.data,
				card_number=form.card_number.data,
				expiration_date=form.expiration_date.data,
				verification_code=form.verification_code.data,
				item_1=form.item_1.data,
				item_1_price=form.item_1_price.data,
				item_2=form.item_2.data,
				item_2_price=form.item_2_price.data,
				item_3=form.item_3.data,
				item_3_price=form.item_3_price.data,
				item_4=form.item_4.data,
				item_4_price=form.item_4_price.data
			)
		underclass_preorder.add()
		return redirect(url_for('main.underclass_preorder'))
	return render_template('main/underclass_preorder.html', form=form)

@main.route('/school_event_photos')
def school_event_photos():
	return render_template('main/school_event_photos.html')

@main.route('/admin_access')
def admin_access():
	return render_template('main/admin_access.html')

@main.route('/make_payment')
def make_payment():
	return render_template('main/make_payment.html')

@main.route('/administrator')
def administrator():
	return render_template('main/administrator.html')

@main.route('/interested_school', methods=['GET', 'POST'])
def interested_school():
	form = RequestInfoForm()
	if form.validate_on_submit():
		request_info = RequestInfo(
				name=form.name.data,
				organization=form.organization.data,
				position=form.position.data,
				address=form.address.data,
				city=form.city.data,
				state=form.state.data,
				zipcode=form.zipcode.data,
				phone=form.phone.data,
				email=form.email.data,
				current_photog=form.current_photog.data,
				comments_questions=form.comments_questions.data
			)
		request_info.add()
		return redirect(url_for('main.interested_school'))
	return render_template('main/interested_school.html', form=form)

@main.route('/retainer_school')
def retained_school():
	return render_template('main/retained_school.html')

@main.route('/information_sheet')
def information_sheet():
	return render_template('main/information_sheet.html')

@main.route('/renew_contract', methods=['GET', 'POST'])
def renew_contract():
	form = RenewContractForm()
	if form.validate_on_submit():
		renewed_contract = RenewedContract(
				as_outlined=form.as_outlined.data,
				e_signature=form.e_signature.data,
				seventeen_eighteen=form.seventeen_eighteen.data,
				eighteen_nineteen=form.eighteen_nineteen.data,
				nineteen_twenty=form.nineteen_twenty.data,
				additional_requests=form.additional_requests.data,
				school=form.school.data,
				address=form.address.data,
				city=form.city.data,
				state=form.state.data,
				zipcode=form.zipcode.data,
				phone=form.phone.data,
				email=form.email.data,
				comments_questions=form.comments_questions.data
			)
		renewed_contract.add()
		return redirect(url_for('main.renew_contract'))
	return render_template('main/renew_contract.html', form=form)

@main.route('/drug_free')
def drug_free():
	return render_template('main/drug_free.html')

@main.route('/non_collusion')
def non_collusion():
	return render_template('main/non_collusion.html')

@main.route('/non_descrimination')
def non_descrimination():
	return render_template('main/non_descrimination.html')

@main.route('/insurance')
def insurance():
	return render_template('main/insurance.html')

@main.route('/sexual_harassment')
def sexual_harassment():
	return render_template('main/sexual_harassment.html')

@main.route('/background_check')
def background_check():
	return render_template('main/background_check.html')

@main.route('/seniors')
def seniors():
	return render_template('main/seniors.html')

@main.route('/deluxe_session')
def deluxe_session():
	return render_template('main/deluxe_session.html')

@main.route('/standard_session')
def standard_session():
	return render_template('main/standard_session.html')
	
@main.route('/yearbook_session')
def yearbook_session():
	return render_template('main/yearbook_session.html')

@main.route('/family_session')
def family_session():
	return render_template('main/family_session.html')

@main.route('/location_session')
def location_session():
	return render_template('main/location_session.html')

@main.route('/faq')
def faq():
	return render_template('main/faq.html')

@main.route('/senior_products')
def senior_products():
	return render_template('main/senior_products.html')

@main.route('/graduate_card_order', methods=['GET', 'POST'])
def graduate_card_order():
	form = GraduateCardOrderForm()
	if form.validate_on_submit():
		grad_card_order = GraduateCardOrder(
				school=form.school.data,
				student_name=form.student_name.data,
				parent_name=form.parent_name.data,
				address=form.address.data,
				city=form.city.data,
				state=form.state.data,
				zipcode=form.zipcode.data,
				phone=form.phone.data,
				email=form.email.data,
				quantity=form.quantity.data,
				image_type=form.image_type.data,
				card_type=form.card_type.data,
				card_number=form.card_number.data,
				expiration_date=form.expiration_date.data,
				verification_code=form.verification_code.data,
				layout=form.layout.data,
				background_color=form.background_color.data,
				font=form.font.data,
				font_color=form.font_color.data,
				image_border=form.image_border.data,
				imprinting=form.imprinting.data,
				promo_code=form.promo_code.data,
				password=form.password.data,
				pose_number=form.pose_number.data
			)
		grad_card_order.add()
		return redirect('main.graduate_card_order')
	return render_template('main/graduate_card_order.html', form=form)

@main.route('/photo_collage')
def photo_collage():
	return render_template('main/photo_collage.html')

@main.route('/portraits')
def portraits():
	return render_template('main/portraits.html')

@main.route('/prekto11')
def prekto11():
	return render_template('main/prekto11.html')

@main.route('/directions')
def directions():
	return render_template('main/directions.html')

@main.route('/history')
def history():
	return render_template('main/history.html')

@main.route('/services')
def services():
	return render_template('main/services.html')

@main.route('/commercial')
def commercial():
	return render_template('main/commercial.html')

@main.route('/dance')
def dance():
	return render_template('main/dance.html')

@main.route('/sports')
def sports():
	return render_template('main/sports.html')

@main.route('/photo_class', methods=['GET', 'POST'])
def photo_class():
	form = PhotoClassForm()
	if form.validate_on_submit():
		photo_class = PhotoClass(
				name=form.name.data,
				address=form.address.data,
				city=form.city.data,
				state=form.state.data,
				zipcode=form.zipcode.data,
				phone=form.phone.data,
				email=form.email.data
			)
		photo_class.add()
		return redirect(url_for('main.photo_class'))
	return render_template('main/photo_class.html', form=form)

@main.route('/remove')
def remove():
	return render_template('main/remove.html')

@main.route('/request_info', methods=['GET', 'POST'])
def request_info():
	form = RequestInfoForm()
	if form.validate_on_submit():
		request_info = RequestInfo(
				name=form.name.data,
				organization=form.organization.data,
				position=form.position.data,
				address=form.address.data,
				city=form.city.data,
				state=form.state.data,
				zipcode=form.zipcode.data,
				phone=form.phone.data,
				email=form.email.data,
				current_photog=form.current_photog.data,
				comments_questions=form.comments_questions.data
			)
		request_info.add()
		return redirect(url_for('main.index'))
	return render_template('main/request_info.html', form=form)

	

app/templates/main/enter_password.html
{% extends 'base/base.html' %}

{% block content %}
	<iframe style="margin-top:50px;" src="http://apps.srphoto.com/lu.fwx" style="display: block;" name="shoot_key" id="shoot_key" height="250" width="100%" frameborder="0">
	Your browser does not support inline frames or is currently configured not to display inline frames.
	</iframe>
	{% include 'base/footer.html' %}
{% endblock %}

app/templates/main/family_session.html
{% extends 'base/base.html' %}

{% block content %}
<div class="text-center">
<h1 style="font-size:150%">Family Session</h1>
	<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" codebase="http://fpdownload.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=7,0,0,0" width="630" height="538" id="JetPhotoView1" align="middle">
	<param name="allowScriptAccess" value="sameDomain" />
	<param name="movie" value="JetPhotoView.swf" />
	<param name="quality" value="High" />
	<param name="bgcolor" value="#ffffff" />
	<embed src="JetPhotoView.swf" quality="High" bgcolor="#ffffff" width="630" height="538" name="JetPhotoView1" align="middle" allowScriptAccess="sameDomain" type="application/x-shockwave-flash" pluginspage="http://www.macromedia.com/go/getflashplayer" />
	</object>
	{% include 'base/footer.html' %}
{% endblock %}

app/templates/main/history.html
{% extends 'base/base.html' %}

{% block style %}
<link rel='stylesheet' type='text/css' href="{{ url_for('static', filename='css/history.css') }}">
{% endblock %}

{% block content %}
 <main>
  	<section class="row">
  		<div class="col-xs-10 col-xs-offset-1">
			<h1 class="text-center">Our History</h1>
			<p>Stuart-Rodgers Photography was founded by Betty Stuart who began her career in photography in 1942 while attending the Medill School of Journalism at Northwestern University. Facing supply and equipment challenges during the end of the Depression and World War II, Betty Stuart Photography became a successful business specializing in people and event photography.</p>
			<p>Portraits and weddings were the primary focus of her work with a new and unique emphasis in a natural and photojournalist style. In 1946 Betty’s husband John Boyd Rodgers joined the company and Stuart-Rodgers Photography was born.</p>
			<p>Over the years the business grew to include school, dance, sports, corporate and commercial photography.</p>
			<p>Today Stuart-Rodgers Photography is a nationally known leader in quality, personalized photography bringing a unique style and commitments to the industry.</p>
		</div>
	</section>
	<section class="row pic-row">
		<div class="col-xs-10 col-xs-offset-1">
			<div class="col-sm-4 text-center">
				<img class="building" src="{{ url_for('static', filename='images/history/SRbuilding1962.jpg') }}">
				<p>Our Evanston Office - 1962</p>
			</div>
			<div class="col-sm-4 text-center">
				<img class="betty-buck" src="{{ url_for('static', filename='images/history/BettyandBuck1945.jpg') }}">
				<p>Buck Betty Rodgers - 1945</p>
			</div>
			<div class="col-sm-4 text-center">			
      			<img class="betty" src="{{ url_for('static', filename='images/history/betty1943.jpg') }}">
				<p>Betty Rodgers - 1943</p>
			</div>
		</div>
	</section>
	{% include 'base/footer.html' %}
{% endblock %}

app/templates/main/information_sheet.html
{% extends 'base/base.html' %}

{% block content %}
<section>
	<div class="row text-center">
		<div class="col-sm-6 col-sm-offset-3">
			<h1 style="font-size:200%">Information Sheet Access</h1>
			<iframe src="http://apps.srphoto.com/infousersframed.htm" style="display: block;" name="I1" id="shoot_key" height="200" width="100%" frameborder="0">
			Your browser does not support inline frames or is currently configured not to display inline frames.
			</iframe>
		</div>
	</div>
</section>
{% include 'base/footer.html' %}
{% endblock %}

app/templates/main/insurance.html
{% extends 'base/base.html' %}

{% block style %}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/contract_policies.css') }}" />
{% endblock %}

{% block content %}
	{% include 'main/partials/policy_certificates.html' %}
	<div class="col-sm-7 col-sm-offset-1 col-xs-10 col-xs-offset-1">
		<div style="margin-top:20px;">
			<p align="center" style="font-size:120%;">Proof of Insurance</p>			
			<img border="0" src="{{ url_for('static', filename='images/contract/insurance.jpg') }}" width="627" height="804">
		</div>
	</div>
	{% include 'base/footer.html' %}
{% endblock %}

app/templates/main/make_payment.html
{% extends 'base/base.html' %}

{% block content %}
	<p align="center">
	<iframe name="I1" src="https://apps.srphoto.com/srpay.fwx" width="100%" height="1550" border="0" frameborder="0">
	Your browser does not support inline frames or is currently configured not to display inline frames.
	</iframe></p>
{% endblock %}

app/templates/main/non_collusion.html
{% extends 'base/base.html' %}

{% block style %}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/contract_policies.css') }}" />
{% endblock %}

{% block content %}
	{% include 'main/partials/policy_certificates.html' %}
	<div class="col-sm-7 col-sm-offset-1 col-xs-10 col-xs-offset-1">
			<div style="margin-top:20px;">			
				<p align="center" style="font-size:120%;">Non-Collusion Affidavit</p>
				<p>By submission of this bid or proposal, the bidder certifies that:</p>
				<p>a) This bid or proposal has been independently arrived at without collusion with any other bidder or with any competitor or potential competitor;</p>
				<p>b) This bid or proposal has not been knowingly disclosed and will not be knowingly disclosed, prior to the opening of bids or proposals for this project, to any other bidder, competitor, or potential competitor;</p>
				<p>c) No attempt has been or will be made to induce any other person, partnership, or corporation to submit or not to submit a bid or proposal or to fix overhead, profit, or cost element of said bid price, or that of any other or to secure any advantage against the Housing Authority;</p>
				<p>d) The person, signing this bid or proposal certifies that he has fully informed himself regarding the accuracy of the statements contained in this certification, and under the penalties of perjury, affirms the truth thereof, such penalties being applicable to the bidder as well as to the person signing in its behalf;</p>
				<p>e) That attached hereto (if a corporate bidder) is a certified copy of the resolution authorizing the execution of this certificate by the signator of this bid or proposal in behalf of the corporate bidder.</p>
				<p>Scott Rodgers, deposes and says that he is President of Stuart-Rodgers Ltd. the party making the foregoing proposal or bid for Photography Services, that such proposal or bid is genuine and not collusive and that all stats herein are true.</p>
				<p>Signature:</p>
				<br>
				<img border=0 width=192 height=62 src="{{ url_for('static', filename='images/contract/sr_signature.png') }}">
				<br>
				Scott Rodgers
				<br>
				<p>President, Stuart-Rodgers Ltd.</p>
			</div>
		</div>
	</div>
	{% include 'base/footer.html' %}
{% endblock %}

app/templates/main/photo_collage.html
{% extends 'base/base.html' %}

{% block content %}
<main class="text-center">
<h1>Photo Collage Examples</h1>
<section class="row">
	<div class="col-xs-10 col-xs-offset-1">
		<div class="col-sm-4 col-xs-12">
			<img class="img-3" alt="photo collage" src="{{ url_for('static', filename='images/photocollage/A_2_186334.jpg') }}">
		</div>
		<div class="col-sm-4 col-xs-12">
			<img class="img-3" alt="photo collage" src="{{ url_for('static', filename='images/photocollage/B_2_186048.jpg') }}">
		</div>		
		<div class="col-sm-4 col-xs-12">
			<img class="img-3" alt="photo collage" src="{{ url_for('static', filename='images/photocollage/c_3_182493.jpg') }}">
		</div>
	</div>
</section>
<section class="row well welld">
	<div class="col-xs-10 col-xs-offset-1">
		<div class="col-sm-4 col-xs-12">
		<img class="img-3" alt="photo collage" src="{{ url_for('static', filename='images/photocollage/D_3_184710.jpg') }}">
		</div>
		<div class="col-sm-4 col-xs-12">
		<img class="img-3" alt="photo collage" src="{{ url_for('static', filename='images/photocollage/guy.jpg') }}">
		</div>
		<div class="col-sm-4 col-xs-12">
		<img class="img-3" alt="photo collage" src="{{ url_for('static', filename='images/photocollage/J_4_185759.jpg') }}">
		</div>
	</div>
</section>
<section class="row">
	<div class="col-xs-10 col-xs-offset-1">
		<div class="col-sm-6">
			<img class="img-2" alt="photo collage" src="{{ url_for('static', filename='images/photocollage/G_4Images.jpg') }}">
		</div>
		<div class="col-sm-">
			<img class="img-2" alt="photo collage" src="{{ url_for('static', filename='images/photocollage/H_4_180209.jpg') }}">
		</div>
	</div>
</section>
</main>
{% endblock %}

app/templates/main/request_info.html
{% extends 'base/base.html' %}
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}
	<div class="row">
		<div class="col-md-6 col-md-offset-3 col-xs-10 col-xs-offset-1">
			<h1 class="text-center">Request Information</h1>
			{{ wtf.quick_form(form) }}
			<br />
		</div>
	</div>
	{% include 'base/footer.html' %}
{% endblock %}

app/templates/main/services.html
{% extends 'base/base.html' %}

{% block style %}
<link rel='stylesheet' type='text/css' href='{{ url_for("static", filename="css/services.css") }}'>
{% endblock %}

{% block content %}
 <main>
  	<section class="row">
  		<div class="col-xs-10 col-xs-offset-1">
  			<h1 class="text-center">Services We Offer</h1>
  			<div class="col-sm-4 text-center">
				<a class="top-three btn btn-default btn-block" href="{{ url_for('main.commercial') }}">
					<span class="glyphicon glyphicon-stats" style="font-size:1.5em;"></span>
					 <br>
					 Commercial
				</a>
			</div>
			<div class="col-sm-4 text-center">
				<a class="top-three btn btn-default btn-block" href="{{ url_for('main.dance') }}">
					<span class="glyphicon glyphicon-camera" style="font-size:1.5em;"></span>
					 <br>
					 Dance
				</a>
			</div>
			<div class="col-sm-4 text-center">
				<a class="top-three btn btn-default btn-block" href="{{ url_for('main.portraits') }}">
					<span class="glyphicon glyphicon-user" style="font-size:1.5em;"></span>
					 <br>
					 Portrait
				</a>
			</div>
		</div>
	</section>
	<section class="row">
		<div class="col-xs-10 col-xs-offset-1">
			<div class="col-sm-4 col-sm-offset-1 text-center">
				<a class=" bottom-two btn btn-default btn-block" href="{{ url_for('main.seniors') }}">
					<span class="glyphicon glyphicon-education" style="font-size:1.5em;"></span>
					 <br>
					 Schools
				</a>
			</div>
			<div class="col-sm-4 col-sm-offset-2 text-center">
				<a class="bottom-two btn btn-default btn-block" href="{{ url_for('main.sports') }}">
					<span class="glyphicon glyphicon-star" style="font-size:1.5em;"></span>
					 <br>
					 Sports
				</a>
			</div>
		</div>
	</section>
</main>
{% endblock %}